### ISSUE TITLE
Request dataset

### ISSUE THREAD

**Issue by phungnhathai** [daugaard/claire#1]
Hi Mr. Daugaard,
This project is good, i wanna run it for test so i don't know about your dataset file. Can you share datafile file for me. I appreciate your sharing

**Comment by houcine1amraoui** [comment]
Dear Mr. Daugaard,
I found your work very interesting, and I will be grateful if you share your dataset with us, so we can see the results. 
For me, it is very difficult to setup a real smart home systems, here in Algeria (north Africa). 
Best regards.
