### ISSUE TITLE
Web Interface Not Accessible

### ISSUE THREAD

**Issue by houcine1amraoui** [daugaard/claire#4]
Dear Daugaard,
The link (http://claire.practicalai.io/) to the web interface that you have created to test the model in **not accessible.**

**Comment by cagnulein** [comment]
hey @daugaard are you still using claire?

**Comment by daugaard** [comment]
This is an old project that is no longer maintained. 
It also looks like the Z-Wave Public website shutdown. Will update the README file to clearly state this.
